// Import necessary modules
import Head from "next/head";
import { AiFillLinkedin, AiFillGithub } from "react-icons/ai";
import { BsFillMoonStarsFill, BsFillSunFill } from "react-icons/bs";
import { AiOutlineCheck } from "react-icons/ai";
import { FaMusic } from "react-icons/fa";
import { FaHeart } from "react-icons/fa";
import { AiOutlineMessage } from "react-icons/ai";
import Image from "next/image";
import React, { useState, useEffect } from "react";

// Define the Home component
function Home() {
  // Define state variables using the useState hook
  const [darkMode, setDarkMode] = useState(true);
  const [imageSrc, setImageSrc] = useState("/Homepage/Avatar.png");
  // Define styles object with different properties
  const styles = {
    circle: {
      backgroundColor: darkMode ? "#7b2cbf" : "yellow",
    },
    square: {
      backgroundColor: darkMode ? "#ff8500" : "#ff8500",
    },
    triangle: {
      backgroundColor: darkMode ? "#e56b6f" : "#d81159",
    },
  };
  // useEffect hook to change the image source depending on the value of darkMode
  useEffect(() => {
    if (darkMode) {
      setImageSrc("/Homepage/Avatar.png");
    } else {
      setImageSrc("/Homepage/Sunglasses.png");
    }
  });
  // Render the following JSX code
  return (
    // Define a div with a conditional class based on darkMode
    // Define the Head component with various metadata
    // Define the main section with various classes
    // Define three divs with different styles and classes
    // Navigation bar
    // Page title
    // Navigation links
    // Dark mode toggle button
    // Resume link
    // Main section
    // Page title
    // Page subtitle
    // Page content
    // Social media links
    // Display headshot
    // Create three div elements containing content listing skills
    // Use shadow-* and rounded-xl classes to give a shadow and rounded borders to the elements.
    // Use bg-* and dark:bg-* classes to provide a different background color based on whether the user has dark mode enabled.
    // Use text-* and dark:text-* classes to provide a different text color based on whether the user has dark mode enabled.
    // Create paragraphs to list skills
    // Define a new section
    // Create a div with flex layout
    // Create 4 divs with absolute position, covers width and height of parent element, and centered
    // Each div contains project icon and link

    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Suzy Lawlor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-orange-100 px-4 md:px-10 lg:px-20 xl:px-40 pt-10 pb-16 md:pb-24 dark:bg-gray-800">
        <section className="relative h-screen md:min-h-screen">
          <div
            style={styles.circle}
            className={`absolute top-1/3 left-1/2 transform -translate-x-1/2 -translate-y-1/2 z-0 w-16 h-16 md:w-64 md:h-64 rounded-full blur-3xl ${
              darkMode ? "" : "mix-blend-multiply"
            } filter animate-blob animation-delay-1000`}
          ></div>
          <div
            style={styles.square}
            className={`absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 z-0 w-16 h-16 md:w-64 md:h-64 rounded-full blur-2xl ${
              darkMode ? "" : "mix-blend-multiply"
            } filter animate-blob animation-delay-2000`}
          ></div>
          <div
            style={styles.triangle}
            className={`absolute top-1/4 right-1/2 transform -translate-x-1/2 -translate-y-1/2 z-0 w-16 h-16 md:w-64 md:h-64 rounded-full blur-3xl ${
              darkMode ? "" : "mix-blend-multiply"
            } filter animate-blob animation-delay-4000`}
          ></div>
          <nav className="text-gray-700 py-5 md:py-10 mb-8 md:mb-12 flex flex-col md:flex-row justify-between items-center dark:text-gray-50">
            <h1 className="font-burtons text-1xl md:text-2xl lg:text-3xl xl:text-4xl mb-2 md:mb-0">
              Developed by Suzy
            </h1>
            <ul className="flex items-center">
              <li>
                {darkMode ? (
                  <BsFillSunFill
                    onClick={() => setDarkMode(!darkMode)}
                    className="cursor-pointer text-xl md:text-3xl mr-4 md:mr-6 lg:mr-8"
                  />
                ) : (
                  <BsFillMoonStarsFill
                    onClick={() => setDarkMode(!darkMode)}
                    className="cursor-pointer text-xl md:text-3xl mr-4 md:mr-6 lg:mr-8"
                  />
                )}
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-700 text-xl md:text-3xl to-blue-400 text-gray-50 px-4 md:px-6 py-2 md:py-3 border-none rounded-md ml-0 md:ml-8"
                  href="/resume"
                  target="_blank"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-6 md:p-10">
            <h2
              style={{ position: "relative", zIndex: 1 }}
              className="text-4xl md:text-8xl py-2 text-orange-200 font-medium dark:text-blue-400"
            >
              Suzy Lawlor
            </h2>
            <h3
              style={{ position: "relative", zIndex: 1 }}
              className="text-xl md:text-4xl py-2 text-gray-900 dark:text-orange-100"
            >
              Developer and designer.
            </h3>
            <p
              style={{ position: "relative", zIndex: 1 }}
              className="text-lg md:text-3xl py-5 leading-8 text-gray-950 dark:text-gray-200 max-w-xl mx-auto"
            >
              Recent full stack web development graduate with a degree in Fine
              Art and a background in digital content creation and marketing
              design.
            </p>
            <div
              style={{ position: "relative", zIndex: 1 }}
              className="text-3xl md:text-5xl flex justify-center gap-8 md:gap-16 py-3 text-gray-50 dark:text-gray-50 mb-4 md:mb-0"
            >
              <a
                href="https://www.linkedin.com/in/suzy-lawlor"
                target="_blank"
                rel="noopener noreferrer"
              >
                <AiFillLinkedin />
              </a>
              <a
                href="https://github.com/suzylawlor"
                target="_blank"
                rel="noopener noreferrer"
              >
                <AiFillGithub />
              </a>
            </div>
          </div>
        </section>
        <section>
          <div className="mx-auto md:w-3/5 lg:w-1/2 flex justify-center">
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-40 h-40 md:w-96 md:h-96 relative overflow-hidden md:-mt-32 lg:-mt-48">
              <Image src={imageSrc} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section className="px-4 md:px-10">
          <div className="text-center">
            <h3 className="text-3xl py-10 dark:text-gray-50">
              A bit about me.
            </h3>
          </div>
          <div className="flex flex-col md:flex-row md:justify-center lg:gap-10">
            <div className="text-center shadow-sm shadow-pink-400 p-6 md:p-10 rounded-xl my-10 bg-orange-100 dark:bg-gray-800 flex-1">
              <h3 className="text-lg text-gray-800 font-medium pt-8 pb-2 dark:text-gray-50">
                Digital Designs
              </h3>
              <p className="py-2 text-gray-800 dark:text-gray-50">
                Creating contemporary designs suited for your needs following
                core digital design theory.
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1 dark:text-gray-50">Photoshop</p>
              <p className="text-gray-800 py-1 dark:text-gray-50">
                Illustrator
              </p>
              <p className="text-gray-800 py-1 dark:text-gray-50">Indesign</p>
              <p className="text-gray-800 py-1 dark:text-gray-50">Pixelmator</p>
            </div>
            <div className="text-center shadow-md shadow-orange-400 p-6 md:p-10 rounded-xl my-10 bg-orange-100 dark:bg-gray-800 flex-1">
              <h3 className="text-lg text-gray-800 font-medium pt-8 pb-2 dark:text-gray-50">
                Clean Code
              </h3>
              <p className="py-2 text-gray-800 dark:text-gray-50">
                Writing clear and maintainable code that solves problems and
                delivers value.
              </p>
              <h4 className="py-4 text-teal-600">Technologies I Use</h4>
              <p className="text-gray-800 py-1 dark:text-gray-50">JavaScript</p>
              <p className="text-gray-800 py-1 dark:text-gray-50">React</p>
              <p className="text-gray-800 py-1 dark:text-gray-50">Node.js</p>
              <p className="text-gray-800 py-1 dark:text-gray-50">Next.js</p>
            </div>
            <div className="text-center shadow-2xl shadow-orange-500 p-6 md:p-10 rounded-xl my-10 bg-orange-100 dark:bg-gray-800 flex-1">
              <h3 className="text-lg text-gray-800 font-medium pt-8 pb-2 dark:text-gray-50">
                Content Creation
              </h3>
              <p className="py-2 text-gray-800 dark:text-gray-50">
                Experienced in creating engaging digital content, gaining skills
                in digital marketing strategy.
              </p>
              <h4 className="py-4 text-teal-600">Projects I have worked</h4>
              <p className="text-gray-800 py-1 dark:text-gray-50">
                Website Design
              </p>
              <p className="text-gray-800 py-1 dark:text-gray-50">
                Client Communication
              </p>
              <p className="text-gray-800 py-1 dark:text-gray-50">
                Social Media Campaigns
              </p>
              <p className="text-gray-800 py-1 dark:text-gray-50">
                Online Invitations
              </p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div className="text-center">
            <h3 className="text-3xl py-20 dark:text-orange-100">
              Some projects to play with.
            </h3>
          </div>
          <div className="flex flex-wrap gap-6 lg:gap-10 justify-center lg:justify-between items-center py-10">
            <div className="w-full md:w-1/2 lg:w-1/5 relative">
              <a
                href="./To-do/todoPage"
                target="_blank"
                className="block relative"
              >
                <div className="rounded-lg overflow-hidden flex items-center justify-center">
                  <AiOutlineCheck className="text-pink-400 text-9xl dark:text-blue-400" />
                </div>
                <div className="absolute top-0 left-0 w-full h-full flex items-center justify-center"></div>
              </a>
            </div>
            <div className="w-full md:w-1/2 lg:w-1/5 relative">
              <a href="/Keyboard" target="_blank" className="block relative">
                <div className="rounded-lg overflow-hidden flex items-center justify-center">
                  <FaMusic className="text-pink-400 text-9xl dark:text-blue-400" />
                </div>
                <div className="absolute top-0 left-0 w-full h-full flex items-center justify-center"></div>
              </a>
            </div>
            <div className="w-full md:w-1/2 lg:w-1/5 relative">
              <a
                href="./Inspiration/Quotes"
                target="_blank"
                className="block relative"
              >
                <div className="rounded-lg overflow-hidden flex items-center justify-center">
                  <FaHeart className="text-pink-400 text-9xl dark:text-blue-400" />
                </div>
                <div className="absolute top-0 left-0 w-full h-full flex items-center justify-center"></div>
              </a>
            </div>
            <div className="w-full md:w-1/2 lg:w-1/5 relative">
              <a
                href="./ChatApp/chatPage"
                target="_blank"
                className="block relative"
              >
                <div className="rounded-lg overflow-hidden flex items-center justify-center">
                  <AiOutlineMessage className="text-pink-400 text-9xl dark:text-blue-400" />
                </div>
                <div className="absolute top-0 left-0 w-full h-full flex items-center justify-center"></div>
              </a>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}

export default Home;
